# Local Proxy Settings
bind-address: '*'
mixed-port: 7890
allow-lan: true
authentication:
  - "myproxy:mysecret"

# Dashboard Settings
external-controller: 0.0.0.0:9090
external-ui: ui
secret: '123456'
log-level: info

# Interface Settings
tun:
    enable: true
    stack: system
    auto-route: true
    dns-hijack:
      - any:53

# DNS Settings
dns:
    enable: true
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    nameserver:
      - 1.1.1.1
      - 8.8.8.8
    fallback: []
    fallback-filter:
        ipcidr:
          - 222.222.222.222/32
          - 111.111.111.111/32

# Tunnel Mode
mode: rule

proxies:
  # Contoh Proxy Rapi
  - gateway: 192.168.60.1 # Gateway modem tujuan
    name: xray-vmess-ws-tls-meprivate-ruangguru
    server: 222.222.222.222 # Server harus berupa IP
    port: 443
    type: vmess
    uuid: 524d3d96-9d82-11ed-1111-06df80e9c580
    sni: my.gegevps.com
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
        path: /worryfree/xray-vmess-ws-tls
        headers:
            Host: my.gegevps.com
  # Contoh Proxy one-line
  - {gateway: 192.168.61.1, name: xray-vmess-ws-tls-meprivate-byuspace, server: 111.111.111.111, port: 443, type: vmess, uuid: 524d3d96-9d82-11ed-1111-06df80e9c580, sni: my.gegevps.com, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /worryfree/xray-vmess-ws-tls, headers: {Host: my.gegevps.com}}}

proxy-groups:
  - name: Load Balance
    type: load-balance
    strategy: round-robin
    disable-udp: false
    proxies:
      - xray-vmess-ws-tls-meprivate-ruangguru
      - xray-vmess-ws-tls-meprivate-byuspace
    url: 'http://www.speedtest.com.sg/test_random_10mb.zip'
    interval: 300

rules:
  - DOMAIN-KEYWORD,youtube,xray-vmess-ws-tls-meprivate-ruangguru
  - DOMAIN-KEYWORD,googlevideo,xray-vmess-ws-tls-meprivate-ruangguru
  - DOMAIN-KEYWORD,drive.google,xray-vmess-ws-tls-meprivate-ruangguru
  - DOMAIN-KEYWORD,googleusercontent,xray-vmess-ws-tls-meprivate-ruangguru
  - MATCH,Load Balance
