#!/bin/bash /etc/rc.common

START=98
STOP=50

dir_root="/etc/gegevps/saclash"
name_config="config.yaml"
clash_core="clash"
boot_delay="3"
watchdog_delay="1"
mkdir -p ${dir_root}

function check_gw(){
    ping -q -w 1 -c 1 $1 > /dev/null && echo ok || echo error
}

function saclash_watchdog(){
    while true; do
        cat ${dir_root}/${name_config} | yq -r '.proxies[] | [.server, .gateway] | @csv' | while read route_obj; do
            ipserver="$(echo -e "${route_obj}" | cut -d ',' -f 1)"
            gateway="$(echo -e "${route_obj}" | cut -d ',' -f 2)"
            
            if [[ $(ip route | grep -wce "${ipserver}") -eq 0 ]]; then
                echo -e "Re-routing ${ipserver} gateway ${gateway}"
                route add ${ipserver} gw ${gateway} &>/dev/null
            else
                echo -e "${ipserver} gateway ${gateway} routed"
            fi
        done
        sleep ${watchdog_delay}
    done
}

start(){
    # Boot Delay
    echo -e "Delay ${boot_delay} secs"
    sleep ${boot_delay}
    
    # Set Route
    cat ${dir_root}/${name_config} | yq -r '.proxies[] | [.server, .gateway] | @csv' | while read route_obj; do
        ipserver="$(echo -e "${route_obj}" | cut -d ',' -f 1)"
        gateway="$(echo -e "${route_obj}" | cut -d ',' -f 2)"
        if [[ "$(check_gw ${gateway})" == "ok" ]]; then
            echo -e "Route ${ipserver} via ${gateway}"
            route add ${ipserver} gw ${gateway} &>/dev/null
            echo -e "online" > /tmp/clash_gateway
        else
            echo -e "Gateway ${gateway} is offline"
            echo -e "offline" > /tmp/clash_gateway
            exit 1
        fi
    done

    # Run Clash
    screen -dmS saclash ${clash_core} -d ${dir_root}
    sleep 3
    
    # Run Watchdog
    export dir_root
    export name_config
    export clash_core
    export watchdog_delay
    export -f saclash_watchdog
    screen -dmS saclash_watchdog bash -c "saclash_watchdog"
}

stop(){
    echo -e "Deleting Previous route"
    cat ${dir_root}/${name_config} | yq -r '.proxies[] | [.server, .gateway] | @csv' | while read route_obj; do
        ipserver="$(echo -e "${route_obj}" | cut -d ',' -f 1)"
        gateway="$(echo -e "${route_obj}" | cut -d ',' -f 2)"
        route del ${ipserver} gw ${gateway} &>/dev/null
    done
    echo -e "Stopping Clash"
    if [[ ! "$(pidof ${clash_core})" == '' ]]; then
        kill $(pidof ${clash_core})
    fi
    echo -e "Stopping Clash Watchdog"
    kill $(screen -ls | grep -oE "[0-9]+\.saclash_watchdog\t" | sed -e "s/\..*$//g")
    echo -e "Clash Stopped"
}
